### ISSUE TITLE
Create version of rule E2 to handle foreign_key based joins

### ISSUE THREAD

**Issue by bendiktv2** [looker-open-source/look-at-me-sideways#130]
Hello, when using version 3.0.0-beta.0, LAMS does not pick up that foreign_key uses the primary key in the view.

In this repo, I have created a minimal reproducible example: https://github.com/bendiktv2/lams-key-bug
It consists of 2 autogenerated views (Create View From Table), and then adding a refinement to each of them, to add pk-dimensions, and a count_distinct measure.
There are 2 explores, 1 which passes E2 with no linting errors (`sql_on: ${view_1.pk1_item_id} = ${works.pk2_item_id} ;;`), and 1 which fails (`foreign_key: pk2_item_id`).

It seems that LAMS is not picking up the use of the refined primary_key in the refined view.

**Comment by fabio-looker** [comment]
Hi, thanks for the bug report!

Unless I'm mistaken, this seems to be a general issue with the E2 logic, and not specifically related to refinements?

I think the rule was just never considered under the usage of `join>foreign_key` since that is an older and often unused form of writing the join.

Code reference: Missing sql/sql_on defaults to empty string and proceeds: https://github.com/looker-open-source/look-at-me-sideways/blob/fabble/v3-extends-refinements/rules/e2.js#L28

Since the logic for `foreign_key` would be slightly different (the join is implicitly against the joined view's `primary_key: yes` dimension, rather than against a naming convention), my initial thought is to have foreign_key joins ignored by this rule, and then make a separate rule for `foreign_key` joins. Thoughts?

**Comment by fabio-looker** [comment]
Pre-release [3.0.0-beta.1](https://www.npmjs.com/package/@looker/look-at-me-sideways/v/3.0.0-beta.1) should fix this.

- foreign_key based joins should never error E2
- In the near future, once 3.0 is properly release, it will be easier to add new rules as minor changes due to rules being opt it, so I can add rule E3 for foreign_key based joins

Thank you for filing this bug, and in advance for letting me know if this resolves things for you!

**Comment by fabio-looker** [comment]
Hi @bendiktv2 - after sitting down and writing out this rule, and writing tests, only when I finally went to document the rule did I realize that this rule perhaps does not make sense? Or perhaps I don't understand it :) In any case, what I implemented is certainly not right...

Using this as an example:

```
explore: orders {
	join: users {
		relationship: many_to_one
		foreign_key: user_id
	}
}
```

The field that is to be provided in the foreign_key is not supposed to be a primary key, it's the foreign key on the orders view. So it wouldn't usually follow the PK naming convention. (It might when the FK happens to be a part of a composite PK, but that is more a coincidence than a rule)

Is there some rule to implement here afterall?

**Comment by fabio-looker** [comment]
v3.1 implements rule [E6](https://looker-open-source.github.io/look-at-me-sideways/rules.html#e6), which ensures that foreign_key based joins declare the right relationship (usually many_to_one, and rarely one_to_one)

As it relates to my previous comment, this new rule is slightly different than E2 in that it does not use the primary key naming convention to enforce cardinality, but rather relies on the assumption that Looker will use the joined view's primary_key dimension, so it must always be a *-to-one join.
