### ISSUE TITLE
K3 with does not respect refinements in version 3.0.0-beta.0

### ISSUE THREAD

**Issue by bendiktv2** [looker-open-source/look-at-me-sideways#132]
Assuming the following autogenerated view:
```LookML
view: my_view {
  sql_table_name: `my-project.my_dataset.my_view`
    ;;

  dimension: user_id {
    type: number
    sql: ${TABLE}.user_id ;;
  }

  measure: count {
    type: count
    drill_fields: []
  }
}
```

And the following refined view:
```LookML
include: "/views/autogenerated_views/my_view.view.lkml"

view: +my_view {
  
  dimension: pk1_user_id {
    primary_key: yes
    hidden: yes
    sql: ${user_id} ;;
  }
  
  dimension: user_id {
    description: "Added description"
    type: string
  }
  
  measure: users {
    label: "Users"
    description: "Unique users"
    type: count_distinct
    sql: ${user_id} ;;
  }
  
  measure: count {
    hidden: yes
  }
}
```

LAMS version 3.0.0-beta.0 reports a K3-error for this view:
```
❌      K3..... m:model_1/v:my_view............................ View my_view contains dimensions declared before PK dimension(s), e.g. user_id
```

**Comment by fabio-looker** [comment]
Sorry, I forgot to update this issue. Upon reflection, the premise of rule K3 (ordering of declarations) only makes sense in linting the files as written, and not in the model as extended/refined, so in 3.0.0-beta.1, I have reverted this check to being file-by-file rather than in the model, and it does not try to use the refined view

More detail is here: https://github.com/looker-open-source/look-at-me-sideways/issues/129

If you have any other feedback, feel free to provide it and I can re-open this ticket.
