### ISSUE TITLE
Opt-in rules specified in manifest.lkml not being recognized (v3)

### ISSUE THREAD

**Issue by rushikaverma-aiq** [looker-open-source/look-at-me-sideways#141]
I'm trying to implement LAMS v3 and for some reason the opt-in rules as specified in the [read.me](https://github.com/looker-open-source/look-at-me-sideways#built-in-linter-rules) just aren't getting picked up during the run.

**screenshot of the `manifest.lkml` file:**
<img width="524" alt="Screen Shot 2023-08-03 at 5 07 42 PM" src="https://github.com/looker-open-source/look-at-me-sideways/assets/109092606/af4d3142-9b99-4abf-916d-fa9890418e45">

**command line args used:**
<img width="186" alt="Screen Shot 2023-08-03 at 5 14 23 PM" src="https://github.com/looker-open-source/look-at-me-sideways/assets/109092606/716e2d29-ea3a-42c2-a4aa-2603efdf89d1">

**screenshot of the run:**
<img width="740" alt="Screen Shot 2023-08-03 at 5 02 44 PM" src="https://github.com/looker-open-source/look-at-me-sideways/assets/109092606/be49bf3d-712c-4db8-a35c-fe267905b303">

Thanks!

**Comment by rushikaverma-aiq** [comment]
I was getting the following `3 moderate severity vulnerabilities` warning so after updating the code, getting a different error. I'm wondering if these vulnerabilities are causing the opt-in rules to not be invoked? Attached below is a screenshot of the code and the error msg

**code:**
<img width="316" alt="Screen Shot 2023-08-04 at 4 11 19 PM" src="https://github.com/looker-open-source/look-at-me-sideways/assets/109092606/3d9cba5a-1927-4484-9d98-9e7fcecdae47">

**error:**
<img width="711" alt="Screen Shot 2023-08-04 at 4 12 11 PM" src="https://github.com/looker-open-source/look-at-me-sideways/assets/109092606/56397cc4-0315-4875-aa48-7b1468f41551">

**Comment by fabio-looker** [comment]
From your first screenshot, I see LAMS is saying "No manifest.lkml file available", so that explains why no rules are being opted in to at that stage. Are you running the command from the root of your LookML repo (and/or using the `cwd` argument to specify a correct working directory?)

I'll look into the dependencies that NPM is warning about and release a patch update for them, however this is not a blocking issue.

The blocking issue seems to be some NPM issue related to /workdir/.DS_Store file permssions, however I am not familiar with what NPM is trying to do here...

I see you are trying to run some NPM package-lock related commands. Could you elaborate why you need these? Since the LAMS package is installed globally with the `-g` flag, I think the subsequent install command probably doesn't do something helpful. Is there an issue with the way I am shipping LAMS' dependencies that you are trying to work around?

**Comment by fabio-looker** [comment]
Also, it seems all 3 of the dependencies with issues are dev dependencies. These are pruned from the npm-shrinkwrap.json file before it is published to NPM, so you should not be seeing this issue when doing `npm install -g @looker-open-source/look-at-me-sideways`. I just tried that myself and did not see any warnings/vulnerabilities:

![image](https://github.com/looker-open-source/look-at-me-sideways/assets/23034640/770beda4-e5b8-42ee-8b5e-f50b04bc5a05)
