### ISSUE TITLE
Run LAMS on just one file or a few files using source arg

### ISSUE THREAD

**Issue by rushikaverma-aiq** [looker-open-source/look-at-me-sideways#144]
Is there a way to run LAMS on just one file or a set of files? I tried using the `--source` arg and passed the file I wanted to test but it looks like the default trumps this single file and lands up running on everything.

Screenshot of the file I want to test it on:
<img width="630" alt="Screen Shot 2023-08-09 at 1 07 03 PM" src="https://github.com/looker-open-source/look-at-me-sideways/assets/109092606/e66d24f7-d781-4db1-99ec-a5dd87631e55">

_Use-case:_ Trying to run the linter on just a set of changed files instead of everything in the project. Using `cd` won't work since I do not want to run the linter on all files under that directory. 

Thanks!

**Comment by fabio-looker** [comment]
Hi @rushikaverma-aiq ! I believe this should work. Perhaps it is just a matter of quoting the argument:
![image](https://github.com/looker-open-source/look-at-me-sideways/assets/23034640/9009d8c4-5e03-4996-992e-07a5d6c63cca)

By the way, since your use case is to do incremental linting, please check out the beta incremental linting feature I just released in v3.1. Essentially, you can use `--output=add-exemptions` to output the current errors as an exemptions file which will prevent them from erroring on future runs.

I am looking for feedback on this new feature to make sure it fits peoples' use cases, so please let me know if you have any feedback on it!

**Comment by fabio-looker** [comment]
Thanks for the bug report. I missed that the promises interface was only added in Node v17: https://nodejs.org/api/readline.html#promises-api

I'll refactor this to use the non-promise interface for greater compatibility and publish it as a patch hopefully today, if not tomorrow.

In the meantime, if you want, this can probably be resolved by running a newer node version.

Thanks again!

**Comment by fabio-looker** [comment]
@racalvomeli Patch release v3.1.1 restores compatibility with Node v14+

**Comment by fabio-looker** [comment]
@rushikaverma-aiq I'll mark this issue as resolved, but if you still have any questions, feel free to follow up here!

**Comment by rushikaverma-aiq** [comment]
> 

Thank you Fabio!
