### ISSUE TITLE
Invalid jsonpath in manifest

### ISSUE THREAD

**Issue by mariana-s-fernandes** [looker-open-source/look-at-me-sideways#178]
Since the latest changes in LAMS, some of the rules I've got set are not working anymore
<img width="630" alt="image" src="https://github.com/looker-open-source/look-at-me-sideways/assets/57906928/7a1d049a-bf01-426b-9801-c29a65111b52">

This is what I have in my manifest file

```

#LAMS
#rule: K7 {} # Provide one `primary_key`
#rule: F1 {} # No cross-view fields
#rule: F2 {} # No view-labeled fields
#rule: F4 {} # Description or hidden
#rule: T1 {} # Triggers use datagroups
#rule: E1 {} # Join with subst'n operator
#rule: E7 {options: {maxLength: 50}}
#rule: W1 {} # Block indentation
```

**Comment by fabio-looker** [comment]
Thanks for the report. This is in v 2.1.8 ?

**Comment by mariana-s-fernandes** [comment]
Yes, that's the version.
LAMS output:

```
Checking rules... 
> E1
> E2
> F1
> F2
> F3
> F4
> K1-2-3-4
> T1
> T2-10
> Rules done!
Checking custom rules...
> K7
> F1
  Skipping F1: it is named like a built-in rule and is not 'custom:yes'
> F2
  Skipping F2: it is named like a built-in rule and is not 'custom:yes'
> F4
  Skipping F4: it is named like a built-in rule and is not 'custom:yes'
> T1
  Skipping T1: it is named like a built-in rule and is not 'custom:yes'
> E1
  Skipping E1: it is named like a built-in rule and is not 'custom:yes'
> E7
> W1
> Custom rules done!
Writing issues.md...
> issues.md done
Linting errors found.
```

**Comment by fabio-looker** [comment]
The error message confirms that you are using v2, but the format of your manifest file suggests that you intend to be using v3.

I think what happened is that when I backported the other issue to 2.1.8, NPM decided to consider that the "latest" version and you may have installed in when you meant to get v3?

I have updated the latest tag on NPM, so an unqualified install command should get you v3.1.3, but you can also try `install @looker/look-at-me-sideways@3` 

Can you try again and let me know if it's working for you?

PS. In any case, I do recommend specifying which major version you want to receive, so that future major changes do not break your configuration

**Comment by mariana-s-fernandes** [comment]
That has fixed it! It is now recognising version 3 as the latest. Thanks!
