### ISSUE TITLE
P1 Rule/Issue 

### ISSUE THREAD

**Issue by prabha-git** [looker-open-source/look-at-me-sideways#180]
Couldn't find out what this error is about, also couldn't find what `P1` rule is. Is it a bug? Any help is appreciated.

<img width="785" alt="image" src="https://github.com/looker-open-source/look-at-me-sideways/assets/3776681/75e2d5fc-f0e6-4aaa-b796-b38f93a4fd6f">

**Comment by fabio-looker** [comment]
Hi @prabha-git 

At a high level, it's a parser error for the LookML in that file, before any linter logic can be applied.

Could you confirm what version of LAMS you are running? (there was an issue yesterday with NPM tagging the wrong version as "latest", and some customers got v2 instead of v3, although that should be fixed already)

Also, if you are willing to share either your whole project or those specific files with me via email, please send them to fabble@google.com

**Comment by prabha-git** [comment]
> Hi @prabha-git
> 
> At a high level, it's a parser error for the LookML in that file, before any linter logic can be applied.
> 
> Could you confirm what version of LAMS you are running? (there was an issue yesterday with NPM tagging the wrong version as "latest", and some customers got v2 instead of v3, although that should be fixed already)
> 
> Also, if you are willing to share either your whole project or those specific files with me via email, please send them to [fabble@google.com](mailto:fabble@google.com)

Send the requested information

**Comment by fabio-looker** [comment]
Issue identified via email, so I will close this out, but feel free to respond if you still notice any issues!

**Comment by prabha-git** [comment]
Yes, It worked as expected after fixing the typos in the comments as part of LAMS rule exemption as you recommended.
