### ISSUE TITLE
LAMS not currently compatible with enterprise github accounts hosted on-prem?

### ISSUE THREAD

**Issue by clpatterson** [looker-open-source/look-at-me-sideways#33]
I'm looking to implement LAMS for a large logistics firm with an enterprise Github account hosted on-prem. Currently the account/repo environment variables passed to the LAMS docker container during build assume the user's github account is hosted by github (https://github.com/<ACCOUNT_NAME>/<REPO_NAME>/).  How can I help make it possible to integrate LAMS with github accounts not hosted by github (https://github.<ENTERPRISE_NAME>.com/<ACCOUNT_NAME>/<REPO_NAME>/)? Is it just the look_at_me_sideways_config.xml file that needs to change? Is it reasonable that enterprise github accounts would follow the same url format https://github.<ENTERPRISE_NAME>.com/ ?

**Comment by fabio-looker** [comment]
Hi!

If you wanted to submit a PR to the project, I think it would be better to parameterize the entire domain name, rather than assuming all enterprises will use a `github` subdomain, or even a .com TLD for that matter.

However, the docker config is really an example, so if you wanted, you could very easily customize it for your customer without necessarily having to submit changes to our repo.

**Comment by clpatterson** [comment]
Fabio, thanx for the quick response. I think parameterizing the entire domain name makes a lot of sense. I'll make the change and submit a pr.
