### ISSUE TITLE
Custom rule to have description mandatory for all explores

### ISSUE THREAD

**Issue by Priyankavl** [looker-open-source/look-at-me-sideways#72]
Hi @fabio-looker , 
Currently I have put an exception for rule [F4.]Non-hidden fields should have descriptions. in the manifest file.
I would like to implement a rule to make it mandatory to include description for all explores in every model.
Can I declare this custom rule in manifest file? If yes, would you please help me with the syntax?
If no, then can it be done using javascript ? Also, please help me with that syntax too.

Thanks,
Priyanka

**Comment by Priyankavl** [comment]
I tried the below syntax, but I guess am missing something

# rule: explore_description {
#  description: "Explores must use description"
#  match: "$.model.*.explore.*"
#  expr_rule: ( === ::match:description true ) ;;
# }

**Comment by fabio-looker** [comment]
Hi @Priyankavl  - Your attempt is pretty close. Liyad uses Javascript's type system as its foundation. Since LookML descriptions are strings, instead of comparing to `true`, I would use  `expr_rule: ( !== ::match:description undefined ) ;;`

I'll mark the ticket as resolved, but if the suggestion doesn't work for you, please let me know!

(Also, PS, I have a prototype custom rule sandbox coming soon that will make it much easier to write and test custom rules)
