### ISSUE TITLE
Add support for folders

### ISSUE THREAD

**Issue by bmschow** [looker-open-source/look-at-me-sideways#9]
Looker 6.16 now allows a folder structure to be present.  LAMS currently does not see files that are in subfolders.

**Comment by bmschow** [comment]
made pull request #11

**Comment by fabio-looker** [comment]
I added a test case for this in node-lookml-parser/subfolders

https://github.com/fabio-looker/node-lookml-parser/tree/subfolders

Adding the `matchBase: true` option to the globOptions there does get the files read, just need to make a few additional tweaks so that the includes are followed as well, and so the output reflects the full path, not just the filename

![image](https://user-images.githubusercontent.com/23034640/63110896-760c7300-bf5a-11e9-91e9-71035c80d4b3.png)

**Comment by fabio-looker** [comment]
I added the functionality to the underlying LookML parser library. Still need to update LAMS' dependencies to use the latest version

**Comment by fabio-looker** [comment]
@bmschow I just updated LAMS to use the 6.0 release of node-lookml-parser. I think this should make all the subdirectory stuff work... would you give it a try and let me know what you're seeing?

**Comment by bmschow** [comment]
@fabio-looker sure, I'll give it a test run today or tomorrow and let you know

**Comment by bmschow** [comment]
@fabio-looker I just gave it a shot on docker.  It still doesn't seem like it's working for folders.

**Comment by fabio-looker** [comment]
Darn. Ok, looks like I may have to work on https://github.com/looker-open-source/look-at-me-sideways/issues/12 first to have a more representative test case from which to work.

**Comment by fabio-looker** [comment]
HI @bmschow - Are you still running into issues? We now have LAMS on npm, so you can use that to help make sure you're on the latest version

**Comment by bmschow** [comment]
Hey, @fabio-looker, I've been really busy lately.  We're still using my forked version and it's working fine, but once I have more time I'll test out the latest version

**Comment by fabio-looker** [comment]
No worries. As of yet, I've not heard any other users raise this issue. So, don't pressure yourself to repro this, I'll just close it out for now, and if you ever experience it again, feel free to reopen.
