### ISSUE TITLE
.gitlab-ci.yml running successfully but issues.md file is not created in gitlab repository

### ISSUE THREAD

**Issue by shreyabnsl09** [looker-open-source/look-at-me-sideways#92]

**Comment by fabio-looker** [comment]
Hi, with the release of v2, the default output mode is no longer via a file (since most CI environments by convention prefer to expose outputs from the command line to users)

Possible solutions include:
- using the command-line output from v2 as the primary method of feedback
- pinning your configuration to use LAMS v1
- passing the `output` parameter to v2 to get the markdown output

https://github.com/looker-open-source/look-at-me-sideways#command-line-arguments

However, if you _are_ passing the `markdown` output parameter and it is not working as expected, please let me know!
