### ISSUE TITLE
How create custom rule prohibiting wildcard includes?

### ISSUE THREAD

**Issue by masutaka** [looker-open-source/look-at-me-sideways#95]
Hi @fabio-looker,

In our project[^1], wildcard `include` was reducing the performance of LookML validation.

Before:

```
include: "/views/**/*.view"
```

[^1]: The number of `.lkml` files is `440`. The total number of lines is `23,217`.

When I stopped wildcard includes, the time was improved from 20 seconds to 11 seconds. So I want to use a custom rule to prohibit wildcard inclusion.
:bulb: Related article: [My LookML Validator is slow! | Looker Community](https://community.looker.com/technical-tips-tricks-1021/my-lookml-validator-is-slow-23592)

After:

```
include: "/views/foo/aaa.view"
include: "/views/foo/bbb.view"
include: "/views/bar/ccc.view"
```

I created the following custom rule in manifest.lkml.

```
# LAMS
# rule: NO_WINC {
#  description: "Stop wildcard include to avoid increasing LookML verification time"
#  match: "$.files[*]"
#  expr_rule: ($not ($boolean ($match "\\*\\*" ::match:include))) ;;
# }
```

Result:

```
❌      NO_WINC files/62....................................... Stop wildcard include to avoid increasing LookML verification time
```

The rules are working fine, but the file names are not being output. Is there a way to output the file name?

**Comment by fabio-looker** [comment]
Hi @masutaka 

Thanks for the question, and this sounds like a great custom rule to implement for performance and maintainability.

Some background that may or may not be interesting: The LookML parser can output the collection of files in a few different ways, but the original method was as an array, and to avoid breaking changes, LAMS has kept using the array-based file representation. It is something I would like to change, so that each file is instead an element in an object keyed by the file path. But that will require a breaking change, so for now we just have the array which is less convenient.

As a workaround, you can return string values from the Liyad expression, and these will be used as the output message, so you can put the file name there.

Here is an example of returning a string value: https://github.com/looker-open-source/look-at-me-sideways/blob/master/__tests__/dummy-projects/16-custom-rule-returning-string/manifest.lkml

Additionally, the file object contains some added metadata, like $file_name, or $file_rel (includes directory). If you ever want to understand what data is available, I suggest running the LookML parser in interactive mode to explore the output, using `lookml-parser --file-output=array --interactive` (this may require separately installing the parser with `npm install -g lookml-parser`)

Finally, if you want to match on individual include statements rather than at the file level, you can use the `path` and `project` to look up ancestor elements (such as the include's file)

This actually happens to be a rule I helped someone else implement, so maybe you can even use it directly as-is

```
# rule: NO_WINC {
 #  match: "$.files.*.include.*"
 #  expr_rule: ( $let file_name ( $get ::project files ::path:2 $file_name ) )
 #             ( $if ( $not ($match "\\*\\.view" ::match) )
 #                   true
 #                   ( $concat "Found wildcard include `"  ::match "` in file `" ::file_name "`" )
 #             ) ;;
 # }
```

**Comment by masutaka** [comment]
Hi @fabio-looker,

Thanks! It works well. :joy:


```
# rule: NO_WINC {
#  description: "Prohibit wildcard include to avoid increasing LookML verification time"
#  match: "$.files.*.include.*"
#  expr_rule: ($let file_path ($get ::project files ::path:2 $file_path))
#             ($if ($match "\\*" ::match)
#                 ($concat "Found wildcard include '" ::match "' in " ::file_path "")
#               true) ;;
# }
```

↓

```
❌      NO_WINC files/1/include/0.............................. Found wildcard include '/views/**/*.view' in explores/aaa.explore.lkml
❌      NO_WINC files/262/include/1............................ Found wildcard include './foo_*.view' in views/bbb.view.lkml
```

**Comment by fabio-looker** [comment]
Hi @jatin-datashells 

I think this is probably just a matter of the changes between LAMS v2 and LAMS v3. With the new file structure in v3, it should actually be simpler. Try this out and let me know if it works for you

```
# rule: NO_WINC {
#  description: "Prohibit wildcard include to avoid increasing LookML verification time"
#  match: "$.file.*.include.*"
#  expr_rule:  ($not ($match "\\*" ::match)) ;;
# }
```

Note that the JSONpath expression now has a singular `file` instead of `files`

**Comment by jatin-datashells** [comment]
Thanks for quick reply @fabio-looker, it did not work. 

I am using - look-at-me-sideways@3.1.3 version. and above code only scanned very less files and gave no error though there are wildcards in system.

if I replace match with :

#  match: "$.file[*]"

Then it scans almost 20x more files and gives no errors, this is also not scanning include files. 

FYI - To check if code is scanning include files I made an error in expr_rule so that it gives error for all scanned files.

**Comment by jatin-datashells** [comment]
Hi @fabio-looker , Thanks for sharing.

I have tried this and few other syntax and none of them seems to be working, below is my manifest file screenshot (if it helps to debug) 
<img width="790" alt="image" src="https://github.com/looker-open-source/look-at-me-sideways/assets/120590230/79e2304b-fd25-45b7-a86d-4a98e530c495">

Also sharing log output, in my system there are 4 files that have wildcard (2 model files and 2 include files) but only 2 errors are displayed of model files. 

<img width="1078" alt="image" src="https://github.com/looker-open-source/look-at-me-sideways/assets/120590230/8bec8c7b-15a3-441a-9864-ac317c798e18">

I have modified LAMS source as below (tried with single and double quotes and without as well): 

`npx --package @looker/look-at-me-sideways@3 lams --reporting=save-no --on-parser-error=info source=**/{*.model,*.explore,*.view,manifest,*_includes,*.*,*}.lkml`

Can you please have a look and suggest what else can be done/tried?

**Comment by fabio-looker** [comment]
Hi @jatin-datashells 

In general, the source parameter should be quoted.

Since LAMS is finding two errors, maybe you can find a pattern among which files it is finding the errors in (is it the model files or the includes files)?

If you want to send me a copy of your project to look at (maybe removing any other files you wouldn't want to share), you can email me at fabble@google.com

**Comment by jatin-datashells** [comment]
Yes I have tried single and double quotes for source parameter and both did not work. 

Only model files are scanned and those 2 errors are from model file only.

Sorry cannot share the project copy, but we have multiple folder ie one for models, another one for view files and one for include files etc.

**Comment by fabio-looker** [comment]
@jatin-datashells You can use temporary/testing rules to output information about what LAMS is scanning. For example, a rule matching "$.file.*" could output a string with the file path

# rule: debug {
#  match: "$.file.*"
#  expr_rule:  ::match:$file_path ;;
# }

**Comment by jatin-datashells** [comment]
Thanks a lot @fabio-looker it is working fine and I am able to scan include files 😀 !

There was a silly mistake, I missed adding hyphens (--) before source parameter due to which include files were not read. As soon as it was corrected, Include files were also scanned and getting errors as expected. 😅

Thanks for helping!
