### ISSUE TITLE
Custom Rule Syntax for Descriptions Entered

### ISSUE THREAD

**Issue by notserp** [looker-open-source/look-at-me-sideways#96]
Hi,

I am trying to input a custom dimension/measure rule based off of the presence of the hidden: yes, and description field not being filled out. However, for some reason its not working. Any ideas?
# rule: unhidden_fields_should_have_descriptions{
# description: "Unhidden fields should have descriptions."
# match: "$.model.*.view.*['dimension','measure'].*"
# expr_rule: ($all
#           (=== ::match:hidden: false)
#           (!== ::match:description undefined)
#       );;
# }

**Comment by fabio-looker** [comment]
Hi @notserp!

Glad to hear you're using LAMS. First of all, if you haven't tried out the [custom rule sandbox](https://looker-open-source.github.io/look-at-me-sideways/tools/rule-sandbox/), I would definitely recommend it. It is a bit hidden, and I am hoping to make it more discoverable in the future.

As to your rule:

1. I have received some passing comments of users running into issues using a `.['dimension','measure'].*` match. I am not sure why though, as I don't have a good repro case since the people who reported it to me just switched to using two separate rules to match each type of object... If you are also seeing this as the cause, I can try to look into it further

2. I'm not sure if just a typ, but there is an extraneous `:` in `(=== ::match:hidden: false)`

2. In addition, as to the logic of the rule, I would also recommend using `(!== ::match:hidden true)` instead, since both `hidden: no` and a missing/undefined `hidden` declaration mean the same thing, since the default/implicit value is no

**Comment by notserp** [comment]
Thanks Fabio,

That is working better now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
